### ISSUE TITLE
Splide addon not working with Vaadin 23

### ISSUE THREAD

**Issue by klauss42** [vaadin-component-factory/vcf-splide-flow#7]
Hi
looks like the Splide component is not working properly with Vaadin 23.
With Vaadin 14 the sample code below renders as follows:
![v14](https://user-images.githubusercontent.com/3908318/212492246-112ae992-2678-41bd-acbb-f7364450bd2f.jpg)

If trying the example inside a normal VerticalLayout, the top image is rendered pretty small:
![v23](https://user-images.githubusercontent.com/3908318/212492259-753f57ed-7eee-4ce8-b370-8347a3e9a4dc.jpg)

If clicking the image, the fullscreen mode opens, but when closed the layout is broken:
![v23-after-fullscreen](https://user-images.githubusercontent.com/3908318/212492345-7181b7a4-81ed-4749-9ca4-5031224d098b.jpg)

The code below is a simple extension of the demo, but using a VerticalLayout instead of the DemoView.
If build with Vaadin 14 it works fine. With Vaadin 23.3.3 the error is easy to reproduce.

```
@Route("splide")
public class SplideView extends VerticalLayout {
    public SplideView() {
        HorizontalLayout sliderLayoutContainer = new HorizontalLayout();
        sliderLayoutContainer.setSpacing(false);
        sliderLayoutContainer.setWidth("600px");
        sliderLayoutContainer.setHeight("400px");
        sliderLayoutContainer.getElement().getStyle().set("margin", "auto");
        sliderLayoutContainer.getElement().getStyle().set("border-style", "solid");
        sliderLayoutContainer.getElement().getStyle().set("border-width", "1px");

        ImageSlide slide1 = new ImageSlide("images/slide_1.png");
        ImageSlide slide2 = new ImageSlide("images/slide_2.png");
        ImageSlide slide3 = new ImageSlide("images/slide_3.png");
        VideoSlide slide4 = new VideoSlide("https://www.youtube.com/watch?v=C78LjVQhejI",
                VideoType.YOUTUBE, "images/slide_4.png");
        ImageSlide slide5 = new ImageSlide("images/slide_5.png");
        ImageSlide slide6 = new ImageSlide("images/slide_6.png");
        ImageSlide slide7 = new ImageSlide("images/slide_7.png");

        Splide slider =
                new Splide(Arrays.asList(slide1, slide2, slide3, slide4, slide5, slide6, slide7));
        slider.setId("images-videos-slider-demo");
        slider.setWidthFull();
        slider.setHeightFull();

        sliderLayoutContainer.add(slider);

        add(sliderLayoutContainer );
    }
}
```
To use Vaadin 23, use the following in the pom.xml:
`<vaadin.version>23.3.3</vaadin.version>
<flow.version>9.0.24</flow.version>
`

Any ideas how to fix or workaround this?

**Comment by paodb** [comment]
Thanks for reporting this. The problem is related to the height calculation on the component initialization. Somehow is ignoring it [here](https://github.com/vaadin-component-factory/vcf-splide-flow/blob/98bedc4f5f04cb48b6579a2aedf74234bcd4a756/vcf-splide/src/main/resources/META-INF/resources/frontend/src/vcf-splide.js#L53). Did some testing and couldn't find a workaround yet. Proper fix needs investigation. This problem is not happening when testing in Vaadin 14.

**Comment by paodb** [comment]
Please check version 1.0.4 that contains a fix for this issue.
